name = "dai-prospects-router"
main = "worker.js"
compatibility_date = "2024-01-01"

routes = [
  { pattern = "*.digital-ai.tech", zone_name = "digital-ai.tech" }
]

[vars]
ORIGIN = "https://prospects.digital-ai.tech"
